version: '3'

services:
  mysql:
    container_name: mm-chat-mysql
    image: mysql:8
    ports:
      - "3360:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: ["--default-authentication-plugin=mysql_native_password"]

  rabbitmq:
    container_name: mm-chat-rabbitmq
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
      - 5630:5672
      - 8090:15672
    environment:
      - RABBITMQ_DEFAULT_USER=mmchat
      - RABBITMQ_DEFAULT_PASS=mmchat
