services:
  ##########
  # SHARED
  ##########
  Mmc.shared.Logger:
    class: ../../../../contexts/shared/infrastructure/WinstonLogger
    arguments: []

  ##########################################################################################
  ########## AUTH
  ##########################################################################################

  #*************
  # User Login
  #*************
  Mmc.auth.AuthUserLogin:
    class: ../../../../contexts/mmc/auth/application/user/AuthUserLogin
    arguments: ['@Mmc.users.UserRepository']

  Apps.mmc.controllers.auth.AuthUserLoginController:
    class: ../../controllers/auth/user/AuthUserLoginController
    arguments: ['@Mmc.auth.AuthUserLogin']

  #***********************
  # User Change Password
  #***********************
  Mmc.auth.AuthUserChangePassword:
    class: ../../../../contexts/mmc/auth/application/user/AuthUserChangePassword
    arguments: ['@Mmc.customers.CustomerRepository']

  Apps.mmc.controllers.auth.AuthUserChangePasswordController:
    class: ../../controllers/auth/user/AuthUserChangePasswordController
    arguments: ['@Mmc.auth.AuthUserChangePassword']

  #*****************
  # Customer Login
  #*****************
  Mmc.auth.AuthCustomerLogin:
    class: ../../../../contexts/mmc/auth/application/customer/AuthCustomerLogin
    arguments: ['@Mmc.customers.CustomerRepository']

  Apps.mmc.controllers.auth.AuthCustomerLoginController:
    class: ../../controllers/auth/customer/AuthCustomerLoginController
    arguments: ['@Mmc.auth.AuthCustomerLogin']

  #****************************
  # Customer Change Password
  #****************************
  Mmc.auth.AuthCustomerChangePassword:
    class: ../../../../contexts/mmc/auth/application/customer/AuthCustomerChangePassword
    arguments: ['@Mmc.customers.CustomerRepository']

  Apps.mmc.controllers.auth.AuthCustomerChangePasswordController:
    class: ../../controllers/auth/customer/AuthCustomerChangePasswordController
    arguments: ['@Mmc.auth.AuthCustomerChangePassword']

  ##########################################################################################
  ########## USERS
  ##########################################################################################
  Mmc.users.UserRepository:
    class: ../../../../contexts/mmc/users/infrastructure/TypeormUserRepository
    arguments: []

  #*************
  # Create
  #*************
  Mmc.users.UserCreate:
    class: ../../../../contexts/mmc/users/application/UserCreate
    arguments: ['@Mmc.users.UserRepository']

  Apps.mmc.controllers.user.UserCreateController:
    class: ../../controllers/user/UserCreateController
    arguments: ['@Mmc.users.UserCreate']

  #*************
  # Get
  #*************
  Mmc.users.UserGet:
      class: ../../../../contexts/mmc/users/application/UserGet
      arguments: ['@Mmc.users.UserRepository']

  Apps.mmc.controllers.user.UserGetController:
    class: ../../controllers/user/UserGetController
    arguments: ['@Mmc.users.UserGet']

  #*************
  # Edit
  #*************
  Mmc.users.UserEdit:
      class: ../../../../contexts/mmc/users/application/UserEdit
      arguments: ['@Mmc.users.UserRepository']

  Apps.mmc.controllers.user.UserEditController:
    class: ../../controllers/user/UserEditController
    arguments: ['@Mmc.users.UserEdit']

  #*************
  # Deactivate
  #*************
  Mmc.users.UserDeactivate:
      class: ../../../../contexts/mmc/users/application/UserDeactivate
      arguments: ['@Mmc.users.UserRepository']

  Apps.mmc.controllers.user.UserDeactivateController:
    class: ../../controllers/user/UserDeactivateController
    arguments: ['@Mmc.users.UserDeactivate']

  ##########################################################################################
  ########## CUSTOMERS
  ##########################################################################################
  Mmc.customers.CustomerRepository:
    class: ../../../../contexts/mmc/customers/infrastructure/TypeormCustomerRepository
    arguments: []

  #*************
  # Create
  #*************
  Mmc.customers.CustomerCreate:
    class: ../../../../contexts/mmc/customers/application/CustomerCreate
    arguments: ['@Mmc.customers.CustomerRepository']

  Apps.mmc.controllers.customer.CustomerCreateController:
    class: ../../controllers/customer/CustomerCreateController
    arguments: ['@Mmc.customers.CustomerCreate']

  #*************
  # Get
  #*************
  Mmc.customers.CustomerGet:
      class: ../../../../contexts/mmc/customers/application/CustomerGet
      arguments: ['@Mmc.customers.CustomerRepository']

  Apps.mmc.controllers.customer.CustomerGetController:
    class: ../../controllers/customer/CustomerGetController
    arguments: ['@Mmc.customers.CustomerGet']

  #*************
  # Edit
  #*************
  Mmc.customers.CustomerEdit:
      class: ../../../../contexts/mmc/customers/application/CustomerEdit
      arguments: ['@Mmc.customers.CustomerRepository']

  Apps.mmc.controllers.customer.CustomerEditController:
    class: ../../controllers/customer/CustomerEditController
    arguments: ['@Mmc.customers.CustomerEdit']

  #*************
  # Deactivate
  #*************
  Mmc.customers.CustomerDeactivate:
      class: ../../../../contexts/mmc/customers/application/CustomerDeactivate
      arguments: ['@Mmc.customers.CustomerRepository']

  Apps.mmc.controllers.customer.CustomerDeactivateController:
    class: ../../controllers/customer/CustomerDeactivateController
    arguments: ['@Mmc.customers.CustomerDeactivate']