services:
  ##########
  # SHARED
  ##########
  Mmc.shared.Logger:
    class: ../../../../contexts/shared/infrastructure/WinstonLogger
    arguments: []

  ##########################################################################################
  ########## AUTH
  ##########################################################################################

  #*************
  # User Login
  #*************
  Mmc.auth.AuthUserLogin:
    class: ../../../../contexts/mmc/auth/application/user/AuthUserLogin
    arguments: ['@Mmc.users.UserRepository']

  Apps.mmc.controllers.auth.AuthUserLoginController:
    class: ../../controllers/auth/user/AuthUserLoginController
    arguments: ['@Mmc.auth.AuthUserLogin']

  #***********************
  # User Change Password
  #***********************
  Mmc.auth.AuthUserChangePassword:
    class: ../../../../contexts/mmc/auth/application/user/AuthUserChangePassword
    arguments: ['@Mmc.customers.CustomerRepository']

  Apps.mmc.controllers.auth.AuthUserChangePasswordController:
    class: ../../controllers/auth/user/AuthUserChangePasswordController
    arguments: ['@Mmc.auth.AuthUserChangePassword']

  #*****************
  # Customer Login
  #*****************
  Mmc.auth.AuthCustomerLogin:
    class: ../../../../contexts/mmc/auth/application/customer/AuthCustomerLogin
    arguments: ['@Mmc.customers.CustomerRepository']

  Apps.mmc.controllers.auth.AuthCustomerLoginController:
    class: ../../controllers/auth/customer/AuthCustomerLoginController
    arguments: ['@Mmc.auth.AuthCustomerLogin']

  #****************************
  # Customer Change Password
  #****************************
  Mmc.auth.AuthCustomerChangePassword:
    class: ../../../../contexts/mmc/auth/application/customer/AuthCustomerChangePassword
    arguments: ['@Mmc.customers.CustomerRepository']

  Apps.mmc.controllers.auth.AuthCustomerChangePasswordController:
    class: ../../controllers/auth/customer/AuthCustomerChangePasswordController
    arguments: ['@Mmc.auth.AuthCustomerChangePassword']

  #*****************
  # Psychic Login
  #*****************
  Mmc.auth.AuthPsychicLogin:
    class: ../../../../contexts/mmc/auth/application/psychic/AuthPsychicLogin
    arguments: ['@Mmc.psychics.PsychicRepository']

  Apps.mmc.controllers.auth.AuthPsychicLoginController:
    class: ../../controllers/auth/psychic/AuthPsychicLoginController
    arguments: ['@Mmc.auth.AuthPsychicLogin']

  #****************************
  # Psychic Change Password
  #****************************
  Mmc.auth.AuthPsychicChangePassword:
    class: ../../../../contexts/mmc/auth/application/psychic/AuthPsychicChangePassword
    arguments: ['@Mmc.psychics.PsychicRepository']

  Apps.mmc.controllers.auth.AuthPsychicChangePasswordController:
    class: ../../controllers/auth/psychic/AuthPsychicChangePasswordController
    arguments: ['@Mmc.auth.AuthPsychicChangePassword']

  ##########################################################################################
  ########## USERS
  ##########################################################################################
  Mmc.users.UserRepository:
    class: ../../../../contexts/mmc/users/infrastructure/TypeormUserRepository
    arguments: []

  #*************
  # Create
  #*************
  Mmc.users.UserCreate:
    class: ../../../../contexts/mmc/users/application/UserCreate
    arguments: ['@Mmc.users.UserRepository']

  Apps.mmc.controllers.user.UserCreateController:
    class: ../../controllers/user/UserCreateController
    arguments: ['@Mmc.users.UserCreate']

  #*************
  # Get
  #*************
  Mmc.users.UserGet:
      class: ../../../../contexts/mmc/users/application/UserGet
      arguments: ['@Mmc.users.UserRepository']

  Apps.mmc.controllers.user.UserGetController:
    class: ../../controllers/user/UserGetController
    arguments: ['@Mmc.users.UserGet']

  #*************
  # Edit
  #*************
  Mmc.users.UserEdit:
      class: ../../../../contexts/mmc/users/application/UserEdit
      arguments: ['@Mmc.users.UserRepository']

  Apps.mmc.controllers.user.UserEditController:
    class: ../../controllers/user/UserEditController
    arguments: ['@Mmc.users.UserEdit']

  #*************
  # Deactivate
  #*************
  Mmc.users.UserDeactivate:
      class: ../../../../contexts/mmc/users/application/UserDeactivate
      arguments: ['@Mmc.users.UserRepository']

  Apps.mmc.controllers.user.UserDeactivateController:
    class: ../../controllers/user/UserDeactivateController
    arguments: ['@Mmc.users.UserDeactivate']

  ##########################################################################################
  ########## CUSTOMERS
  ##########################################################################################
  Mmc.customers.CustomerRepository:
    class: ../../../../contexts/mmc/customers/infrastructure/TypeormCustomerRepository
    arguments: []

  #*************
  # Create
  #*************
  Mmc.customers.CustomerCreate:
    class: ../../../../contexts/mmc/customers/application/CustomerCreate
    arguments: ['@Mmc.customers.CustomerRepository']

  Apps.mmc.controllers.customer.CustomerCreateController:
    class: ../../controllers/customer/CustomerCreateController
    arguments: ['@Mmc.customers.CustomerCreate']

  #*************
  # Get
  #*************
  Mmc.customers.CustomerGet:
      class: ../../../../contexts/mmc/customers/application/CustomerGet
      arguments: ['@Mmc.customers.CustomerRepository']

  Apps.mmc.controllers.customer.CustomerGetController:
    class: ../../controllers/customer/CustomerGetController
    arguments: ['@Mmc.customers.CustomerGet']

  #*************
  # Edit
  #*************
  Mmc.customers.CustomerEdit:
      class: ../../../../contexts/mmc/customers/application/CustomerEdit
      arguments: ['@Mmc.customers.CustomerRepository']

  Apps.mmc.controllers.customer.CustomerEditController:
    class: ../../controllers/customer/CustomerEditController
    arguments: ['@Mmc.customers.CustomerEdit']

  #*************
  # Deactivate
  #*************
  Mmc.customers.CustomerDeactivate:
      class: ../../../../contexts/mmc/customers/application/CustomerDeactivate
      arguments: ['@Mmc.customers.CustomerRepository']

  Apps.mmc.controllers.customer.CustomerDeactivateController:
    class: ../../controllers/customer/CustomerDeactivateController
    arguments: ['@Mmc.customers.CustomerDeactivate']

  ##########################################################################################
  ########## PSYCHICS
  ##########################################################################################
  Mmc.psychics.PsychicRepository:
    class: ../../../../contexts/mmc/psychics/infrastructure/TypeormPsychicRepository
    arguments: []

  #*************
  # Create
  #*************
  Mmc.psychics.PsychicCreate:
    class: ../../../../contexts/mmc/psychics/application/PsychicCreate
    arguments: ['@Mmc.psychics.PsychicRepository']

  Apps.mmc.controllers.psychic.PsychicCreateController:
    class: ../../controllers/psychic/PsychicCreateController
    arguments: ['@Mmc.psychics.PsychicCreate']

  #*************
  # Get
  #*************
  Mmc.psychics.PsychicGet:
      class: ../../../../contexts/mmc/psychics/application/PsychicGet
      arguments: ['@Mmc.psychics.PsychicRepository']

  Apps.mmc.controllers.psychic.PsychicGetController:
    class: ../../controllers/psychic/PsychicGetController
    arguments: ['@Mmc.psychics.PsychicGet']

  #*************
  # Edit
  #*************
  Mmc.psychics.PsychicEdit:
      class: ../../../../contexts/mmc/psychics/application/PsychicEdit
      arguments: ['@Mmc.psychics.PsychicRepository']

  Apps.mmc.controllers.psychic.PsychicEditController:
    class: ../../controllers/psychic/PsychicEditController
    arguments: ['@Mmc.psychics.PsychicEdit']

  #*************
  # Deactivate
  #*************
  Mmc.psychics.PsychicDeactivate:
      class: ../../../../contexts/mmc/psychics/application/PsychicDeactivate
      arguments: ['@Mmc.psychics.PsychicRepository']

  Apps.mmc.controllers.psychic.PsychicDeactivateController:
    class: ../../controllers/psychic/PsychicDeactivateController
    arguments: ['@Mmc.psychics.PsychicDeactivate']

  ##########################################################################################
  ########## CHAT SESSION
  ##########################################################################################
  Mmc.chatSessions.ChatSessionRepository:
    class: ../../../../contexts/mmc/chatSessions/infrastructure/TypeormChatSessionRepository
    arguments: []

  #*************
  # Create
  #*************
  Mmc.chatSessions.ChatSessionCreate:
    class: ../../../../contexts/mmc/chatSessions/application/ChatSessionCreate
    arguments: [
      '@Mmc.chatSessions.ChatSessionRepository',
      '@Mmc.customers.CustomerGet',
      '@Mmc.psychics.PsychicGet',
      '@Mmc.users.UserGet'
      ]

  Apps.mmc.controllers.chatSession.ChatSessionCreateController:
    class: ../../controllers/chatSession/ChatSessionCreateController
    arguments: ['@Mmc.chatSessions.ChatSessionCreate']

  #*************
  # Get
  #*************
  Mmc.chatSessions.ChatSessionGet:
      class: ../../../../contexts/mmc/chatSessions/application/ChatSessionGet
      arguments: [
        '@Mmc.chatSessions.ChatSessionRepository',
        '@Mmc.chatSessionMessages.ChatSessionMessageList'
      ]

  Apps.mmc.controllers.chatSession.ChatSessionGetController:
    class: ../../controllers/chatSession/ChatSessionGetController
    arguments: ['@Mmc.chatSessions.ChatSessionGet']

  #*************
  # Deactivate
  #*************
  Mmc.chatSessions.ChatSessionDeactivate:
      class: ../../../../contexts/mmc/chatSessions/application/ChatSessionDeactivate
      arguments: ['@Mmc.chatSessions.ChatSessionRepository']

  Apps.mmc.controllers.chatSession.ChatSessionDeactivateController:
    class: ../../controllers/chatSession/ChatSessionDeactivateController
    arguments: ['@Mmc.chatSessions.ChatSessionDeactivate']

  ##########################################################################################
  ########## CHAT SESSION MESSAGE
  ##########################################################################################
  Mmc.chatSessionMessages.ChatSessionMessageRepository:
    class: ../../../../contexts/mmc/chatSessionMessages/infrastructure/TypeormChatSessionMessageRepository
    arguments: []

  #*************
  # Create
  #*************
  Mmc.chatSessionMessages.ChatSessionMessageCreate:
    class: ../../../../contexts/mmc/chatSessionMessages/application/ChatSessionMessageCreate
    arguments: [
      '@Mmc.chatSessionMessages.ChatSessionMessageRepository',
      '@Mmc.chatSessions.ChatSessionGet',
      '@Mmc.customers.CustomerGet',
      '@Mmc.psychics.PsychicGet',
      '@Mmc.users.UserGet'
    ]

  Apps.mmc.controllers.chatSessionMessage.ChatSessionMessageCreateController:
    class: ../../controllers/chatSessionMessage/ChatSessionMessageCreateController
    arguments: ['@Mmc.chatSessionMessages.ChatSessionMessageCreate']

  #*************
  # Get
  #*************
  Mmc.chatSessionMessages.ChatSessionMessageGet:
      class: ../../../../contexts/mmc/chatSessionMessages/application/ChatSessionMessageGet
      arguments: ['@Mmc.chatSessionMessages.ChatSessionMessageRepository']

  Apps.mmc.controllers.chatSessionMessage.ChatSessionMessageGetController:
    class: ../../controllers/chatSessionMessage/ChatSessionMessageGetController
    arguments: ['@Mmc.chatSessionMessages.ChatSessionMessageGet']

  #*************
  # List
  #*************
  Mmc.chatSessionMessages.ChatSessionMessageList:
      class: ../../../../contexts/mmc/chatSessionMessages/application/ChatSessionMessageList
      arguments: ['@Mmc.chatSessionMessages.ChatSessionMessageRepository']

  #*************
  # Delete
  #*************
  Mmc.chatSessionMessages.ChatSessionMessageDelete:
      class: ../../../../contexts/mmc/chatSessionMessages/application/ChatSessionMessageDelete
      arguments: ['@Mmc.chatSessionMessages.ChatSessionMessageRepository']

  Apps.mmc.controllers.chatSessionMessage.ChatSessionMessageDeleteController:
    class: ../../controllers/chatSessionMessage/ChatSessionMessageDeleteController
    arguments: ['@Mmc.chatSessionMessages.ChatSessionMessageDelete']