services:
  ##########
  # SHARED
  ##########
  Mmc.shared.Logger:
    class: ../../../../contexts/shared/infrastructure/WinstonLogger
    arguments: []

  ##########################################################################################
  ########## AUTH
  ##########################################################################################

  #***********
  # Login
  #***********
  Mmc.auth.AuthLogin:
    class: ../../../../contexts/mmc/auth/application/AuthLogin
    arguments: ['@Mmc.users.UserRepository']

  Apps.mmc.controllers.auth.AuthLoginController:
    class: ../../controllers/auth/AuthLoginController
    arguments: ['@Mmc.auth.AuthLogin']

  #***********
  # Change Password
  #***********
  Mmc.auth.AuthChangePassword:
    class: ../../../../contexts/mmc/auth/application/AuthChangePassword
    arguments: ['@Mmc.users.UserRepository']

  Apps.mmc.controllers.auth.AuthChangePasswordController:
    class: ../../controllers/auth/AuthChangePasswordController
    arguments: ['@Mmc.auth.AuthChangePassword']

  ##########################################################################################
  ########## USERS
  ##########################################################################################
  Mmc.users.UserRepository:
    class: ../../../../contexts/mmc/users/infrastructure/TypeormUserRepository
    arguments: []

  #***********
  # Create
  #***********
  Mmc.users.UserCreate:
    class: ../../../../contexts/mmc/users/application/UserCreate
    arguments: ['@Mmc.users.UserRepository']

  Apps.mmc.controllers.user.UserCreateController:
    class: ../../controllers/user/UserCreateController
    arguments: ['@Mmc.users.UserCreate']

  #***********
  # Get
  #***********
  Mmc.users.UserGet:
      class: ../../../../contexts/mmc/users/application/UserGet
      arguments: ['@Mmc.users.UserRepository']

  Apps.mmc.controllers.user.UserGetController:
    class: ../../controllers/user/CustomerGetController
    arguments: ['@Mmc.users.UserGet']

  #***********
  # Edit
  #***********
  Mmc.users.UserEdit:
      class: ../../../../contexts/mmc/users/application/UserEdit
      arguments: ['@Mmc.users.UserRepository']

  Apps.mmc.controllers.user.UserEditController:
    class: ../../controllers/user/CustomerEditController
    arguments: ['@Mmc.users.UserEdit']

  #***********
  # Deactivate
  #***********
  Mmc.users.UserDeactivate:
      class: ../../../../contexts/mmc/users/application/UserDeactivate
      arguments: ['@Mmc.users.UserRepository']

  Apps.mmc.controllers.user.UserDeactivateController:
    class: ../../controllers/user/UserDeactivateController
    arguments: ['@Mmc.users.UserDeactivate']

  ##########################################################################################
  ########## CUSTOMERS
  ##########################################################################################
  Mmc.customers.CustomerRepository:
    class: ../../../../contexts/mmc/customers/infrastructure/TypeormCustomerRepository
    arguments: []

  #***********
  # Create
  #***********
  Mmc.customers.CustomerCreate:
    class: ../../../../contexts/mmc/customers/application/CustomerCreate
    arguments: ['@Mmc.customers.CustomerRepository']

  Apps.mmc.controllers.customer.CustomerCreateController:
    class: ../../controllers/customer/CustomerCreateController
    arguments: ['@Mmc.customers.CustomerCreate']

  #***********
  # Get
  #***********
  Mmc.customers.CustomerGet:
      class: ../../../../contexts/mmc/customers/application/CustomerGet
      arguments: ['@Mmc.customers.CustomerRepository']

  Apps.mmc.controllers.customer.CustomerGetController:
    class: ../../controllers/customer/CustomerGetController
    arguments: ['@Mmc.customers.CustomerGet']

  #***********
  # Edit
  #***********
  Mmc.customers.CustomerEdit:
      class: ../../../../contexts/mmc/customers/application/CustomerEdit
      arguments: ['@Mmc.customers.CustomerRepository']

  Apps.mmc.controllers.customer.CustomerEditController:
    class: ../../controllers/customer/CustomerEditController
    arguments: ['@Mmc.customers.CustomerEdit']

  #***********
  # Deactivate
  #***********
  Mmc.customers.CustomerDeactivate:
      class: ../../../../contexts/mmc/customers/application/CustomerDeactivate
      arguments: ['@Mmc.customers.CustomerRepository']

  Apps.mmc.controllers.customer.CustomerDeactivateController:
    class: ../../controllers/customer/CustomerDeactivateController
    arguments: ['@Mmc.customers.CustomerDeactivate']