services:
  #########
  # SHARED
  #########
  Mmc.shared.Logger:
    class: ../../../../contexts/shared/infrastructure/WinstonLogger
    arguments: []

  #########
  # USERS
  #########
  Mmc.users.UserRepository:
    class: ../../../../contexts/mmc/users/infrastructure/TypeormUserRepository
    arguments: []

  Mmc.users.UserCreate:
    class: ../../../../contexts/mmc/users/application/UserCreate
    arguments: ["@Mmc.users.UserRepository"]

  Apps.mmc.controllers.user.UserCreateController:
    class: ../../controllers/user/UserCreateController
    arguments: ["@Mmc.users.UserCreate"]

  #########
  # AUTH
  #########
  Mmc.auth.AuthLogin:
    class: ../../../../contexts/mmc/auth/application/AuthLogin
    arguments: ["@Mmc.users.UserRepository"]

  Apps.mmc.controllers.auth.AuthLoginController:
    class: ../../controllers/auth/AuthLoginController
    arguments: ["@Mmc.auth.AuthLogin"]